Repository cardano-foundation/developer-portal, pull requests merged in 2022-07, with the labels that each got.

#664 Added cscli to builder tools with new 'CLI' tag and corresponding getting started docs
  docs/get-started/cscli.md
  sidebars.js
  src/data/builder-tools.js
  src/data/builder-tools/cscli.png
Labels: builder tool

#665 new pages: Air Gap Environment, Secure Transaction Workflow
  docs/get-started/air-gap.md
  docs/get-started/secure-workflow.md
  sidebars.js
  static/img/get-started/air-gap/10-software-choices.png
  static/img/get-started/air-gap/20-installation-type.png
  static/img/get-started/air-gap/30-encrypt-disk.png
  static/img/get-started/air-gap/35-disk-encrypted.png
  yarn.lock
Labels: documentation

#667 Add eUTxO showcase
  src/data/showcase/eutxo.png
  src/data/showcases.js
Labels: showcase

#668 Add period at the end of description for all showcases/builder tools
  src/data/builder-tools.js
  src/data/showcases.js
Labels: documentation

#661 fix: broken link on integrate cardano page
  docs/get-started/overview.md
Labels: bug

#672 Add ImperatorLang
  src/data/builder-tools.js
  src/data/builder-tools/imperator.png
Labels: builder tool

#677 Name change of community advisor role
  docs/governance/project-catalyst.md
  src/data/showcase/roundtable.png
  src/data/showcases.js
Labels: documentation

#684 Modify tagline on main page
  docusaurus.config.js
Labels: documentation

#685 marlowe playground links updated
  docs/smart-contracts/marlowe.md
Labels: documentation

#690 Add Koios Interview to Developer Blog section
  blog/2022-07-11-july.md
  static/img/devblog/koios-dark.png
  static/img/devblog/koios-light.png
Labels: blog

#645 Add showcase Paradiso
  src/data/showcase/paradiso.png
  src/data/showcases.js
Labels: showcase

#695 Fixed broken link on plutus.md
  docs/smart-contracts/plutus.md
Labels: bug, documentation

#692 Modify build scripts: Replace fs.rmdir with fs.rm
  scripts/cip.ts
  scripts/token-registry.ts
Labels: script

#687 Fix broken link to key pairs
  docs/stake-pool-guide/introduction.md
Labels: documentation

#679 Added HAZELnet for Community Creation
  src/data/showcase/hazelnet.png
  src/data/showcases.js
Labels: showcase

#703 Fix hover effect on buttons & make border thicker
  src/css/custom.css
  src/pages/styles.module.css
Labels: bug

#706 rectified --mint= syntax to correct form --mint
  docs/native-tokens/minting.md
Labels: documentation

#710 Update weekly report
  WEEKLY_REPORT.md
Labels: documentation

#682 CVM - Cardano Version Manager :)
  src/data/builder-tools/cvm.png
  src/data/showcases.js
Labels: builder tool

#709 Fix broken images for builder tools Lucid and Pallas
  src/data/builder-tools.js
  src/data/builder-tools/lucid.png
  src/data/builder-tools/lucid.svg
  src/data/builder-tools/pallas.png
  src/data/builder-tools/pallas.svg
Labels: bug

#708 Fix broken links for Jobs at dcSpark and EMURGO
  docs/careers.md
Labels: documentation

#712 Fix broken code consoles in CSCLI markdown file
  docs/get-started/cscli.md
Labels: bug
