Repository cardano-foundation/developer-portal, pull requests merged in 2022-08, with the labels that each got.

#719 Add dapps-on-cardano showcase
  src/data/showcase/dapps-on-cardano.png
  src/data/showcases.js
Labels: showcase

#696 Modify broken link
  docs/get-started/technical-concepts.md
Labels: bug

#738 Revamp stake pool course
  docs/stake-pool-guide/best-practices.md
  docs/stake-pool-guide/get-started.md
  docs/stake-pool-guide/install-configure-node.md
  docs/stake-pool-guide/introduction.md
  docs/stake-pool-guide/pool-maintainance.md
  docs/stake-pool-guide/pre-requisites.md
  docs/stake-pool-guide/register-pool.md
  docs/stake-pool-guide/stake-pool-basics.md
  docs/stake-pool-guide/tools-links.md
  sidebars.js
Labels: documentation

#743 [Typo] [minting.md] "Amout" -> "Amount"
  docs/native-tokens/minting.md
Labels: typo
