Repository cardano-foundation/developer-portal, pull requests merged in 2023-04, with the labels that each got.

#1014 Add changelog for March
  CHANGELOG.md
Labels: changelog

#1013 Update Docusaurus to 2.4.0
  package.json
Labels: dependencies

#1027 Add plu-ts to Builder Tools + Smart Contract platforms
  docs/get-started/plu-ts.md
  docs/smart-contracts/overview.md
  docs/smart-contracts/plu-ts.md
  sidebars.js
  src/data/builder-tools.js
  src/data/builder-tools/plu-ts.png
  src/data/builder-tools/plu-ts.svg
  static/img/plu_ts-logo.svg
Labels: builder tool

#1030 OpShin: Update and extend the example section
  docs/smart-contracts/opshin.md
Labels: documentation

#1032 POS tutorial - change 'clone' to 'fork' typo
  docs/integrate-cardano/point-of-sale.md
Labels: typo

#1034 Fix OG image for catalyst page
  docs/governance/project-catalyst.md
Labels: bug

#1039 Fix mobile jump bug when using search bar in Showcase/Tool pages
  src/pages/showcase/index.js
  src/pages/tools/index.js
Labels: bug

#1036 Receiving Payments (Blockfrost API) - Minor Documentation fix
  docs/integrate-cardano/point-of-sale.md
Labels: documentation

#1037 Resolve unique key issue in showcase and builder tools page
  src/components/showcase/ShowcaseCard/index.js
  src/pages/showcase/index.js
  src/pages/showcase/styles.module.css
  src/pages/tools/index.js
  src/pages/tools/styles.module.css
Labels: enhancement

#1040 Add aada.finance to Showcase
  src/data/showcase/aada-finance.png
  src/data/showcases.js
Labels: showcase

#1033 Revamp stake pool course | Adding Register Stake Pool
  docs/stake-pool-guide/register-stake-address.md
  sidebars.js
Labels: documentation, stake pool operators

#1042 Add flipr.io to Showcase
  src/data/showcase/flipr.png
  src/data/showcases.js
Labels: showcase
