Repository cardano-foundation/developer-portal, pull requests merged in 2023-10, with the labels that each got.

#1152 cardano-node install: ldconfig after building libsecp256k
  docs/get-started/installing-cardano-node.md
  docs/operate-a-stake-pool/node-installation-process.md
Labels: documentation

#1155 SPO Overview: remove defunct marketing page
  docs/operate-a-stake-pool/overview.md
Labels: documentation

#1156 SPO Overview: remove pool.vet link
  docs/operate-a-stake-pool/overview.md
Labels: documentation

#1153 Add Changelog for September
  CHANGELOG.md
Labels: changelog

#1154 Update Docusaurus to 2.4.3
  package.json
Labels: dependencies

#1159 Add DexHunter to Showcase
  src/data/showcase/dexhunter.png
  src/data/showcases.js
Labels: showcase

#1164 Smart Contracts overview: bit of language cleanup
  docs/smart-contracts/overview.md
Labels: typo

#1158 Add DROPSPOT to Showcase
  src/data/showcase/dropspot.png
  src/data/showcases.js
Labels: showcase

#1168 Aiken get started: Fix broken examples link
  docs/get-started/aiken.md
Labels: documentation
