Repository cardano-foundation/developer-portal, pull requests merged in 2023-12, with the labels that each got.

#1150 Cardano Node Installation process: add cabal update
  docs/operate-a-stake-pool/node-installation-process.md
Labels: documentation

#1178 Frankenwallet: Edit for grammar, formatting + correctness
  .github/actions/yarn-build/Dockerfile
  docs/get-started/air-gap.md
  docs/operate-a-stake-pool/frankenwallet.md
Labels: documentation, help wanted

#1180 CONTRIBUTING.md: Tiny grammar mistake
  CONTRIBUTING.md
Labels: typo
