Repository cardano-foundation/developer-portal, pull requests merged in 2024-10, with the labels that each got.

#1334 Governance actions: Fix constitution link
  docs/get-started/cardano-cli/governance/governance-actions.md
Labels: documentation

#1341 Installing Cardano Node: update latest mainnet version
  docs/get-started/cardano-node/installing-cardano-node.md
Labels: documentation

#1317 Participate in Governance: Add CIP Wiki as reference
  docs/governance/overview.md
Labels: documentation

#1342 Update Dockerfile - Lets try rollback to lts-alpine
  .github/actions/yarn-build/Dockerfile
Labels: dependencies

#1345 Add pg_cardano and CFD to Builder Tools
  src/data/builder-tools.js
  src/data/builder-tools/cfd.png
  src/data/builder-tools/pg_cardano.png
Labels: builder tool
