Repository cardano-foundation/developer-portal, pull requests merged in 2024-04, with the labels that each got.

#1241 SPO node installation: Update cabal version
  docs/operate-a-stake-pool/node-installation-process.md
Labels: documentation

#1240 plu-ts: Fix broken main documentation link
  docs/smart-contracts/plu-ts.md
Labels: typo

#1242 Add changelog for March 2024
  CHANGELOG.md
Labels: changelog

#1243 Fix typos in docs
  docs/get-started/blockfrost/open-source.md
  docs/get-started/cardano-developer-community.md
  docs/get-started/cardano-serialization-lib/create-react-app.md
  docs/get-started/cardano-wallet-js.md
  docs/get-started/cardanosharp-wallet.md
  docs/get-started/koios.md
  docs/get-started/mesh/transactions-basic.md
  docs/get-started/mesh/transactions-smart-contract.md
  docs/get-started/mesh/transactions-staking.md
  docs/get-started/plu-ts.md
  docs/get-started/secure-workflow.md
  docs/get-started/technical-concepts.md
  docs/get-started/testnets-and-devnets.md
  docs/integrate-cardano/creating-wallet-faucet.md
  docs/integrate-cardano/listening-for-payments-cli.md
  docs/integrate-cardano/listening-for-payments-wallet.md
  docs/integrate-cardano/overview.md
  docs/integrate-cardano/user-wallet-authentication.md
  docs/native-tokens/minting-nfts.md
  docs/operate-a-stake-pool/ansible-cardano-node.md
  docs/operate-a-stake-pool/cardano-relay-configuration.md
  docs/operate-a-stake-pool/frankenwallet.md
  docs/operate-a-stake-pool/guild-ops-suite.md
  docs/operate-a-stake-pool/hardening-server.md
  docs/operate-a-stake-pool/improve-grafana-security.md
  docs/operate-a-stake-pool/introduction-to-cardano.md
  docs/operate-a-stake-pool/stake-pool-networking.md
  docs/portal-contribute.md
  docs/smart-contracts/marlowe.md
  docs/smart-contracts/overview.md
  docs/smart-contracts/plu-ts.md
  docs/smart-contracts/plutus.md
  docs/transaction-metadata/retrieving-metadata.md
Labels: typo
