Repository cardano-foundation/developer-portal, pull requests merged in 2024-01, with the labels that each got.

#1187 SPO node installation: Update links moved to IntersectMBO
  docs/operate-a-stake-pool/node-installation-process.md
Labels: documentation

#1184 add liqwid to showcase
  src/data/showcase/liqwid.png
  src/data/showcases.js
Labels: showcase

#1192 Vespr Blog added
  blog/2024-01-22-january.md
  static/img/devblog/vespr-dark.svg
  static/img/devblog/vespr-light.svg
  static/img/og/og-blog-vespr.png
Labels: blog

#1194 Air gap: Fix grammar problem from last edit
  docs/get-started/air-gap.md
Labels: typo

#1201 Marlowe page: update & curate links
  docs/smart-contracts/marlowe.md
Labels: documentation
