Repository cardano-foundation/developer-portal, pull requests merged in 2024-09, with the labels that each got.

#1321 Register as a DRep: fix misspelled name
  docs/get-started/cardano-cli/governance/register-drep.md
Labels: typo

#1320 Cardano Node: add dynamic block forging + fix correct source for config files
  docs/get-started/cardano-node/dynamic-block-forging.md
  docs/get-started/cardano-node/running-cardano.md
Labels: documentation

#1319 Governance: add Conway overview + diagram
  docs/get-started/cardano-cli/governance/governance.md
  static/img/cli/conwayup.png
Labels: documentation

#1331 Governance Showcase and Builder Tools Category
  src/data/builder-tools.js
  src/data/builder-tools/ledgersync.jpg
  src/data/builder-tools/rewardcalc.jpg
  src/data/builder-tools/zhuli.jpg
  src/data/showcase/ccportal.jpg
  src/data/showcase/changwatch.jpg
  src/data/showcase/govtools.jpg
  src/data/showcases.js
Labels: showcase, builder tool

#1330 Remove Plutus Playground from Builder Tools
  src/data/builder-tools.js
Labels: builder tool
