Repository cardano-foundation/developer-portal, pull requests merged in 2025-05, with the labels that each got.

#1438 Showcase: add Accounting category
  src/data/showcases.js
Labels: enhancement, showcase

#1462 Getting cardano-node: Remove shell prompt characters
  docs/get-started/cardano-node/installing-cardano-node.md
Labels: documentation

#1459 Add ADAM to showcase
  src/data/showcase/adam.png
  src/data/showcases.js
Labels: showcase

#1470 Integrate Cardano: add Exchange Integrations
  docs/integrate-cardano/exchange-integrations.md
  docs/integrate-cardano/overview.md
  sidebars.js
Labels: documentation

#1471 Stake address registration: Add missing signature by stake.skey
  docs/get-started/cardano-cli/get-started/stakeaddress-registration.md
Labels: documentation

#1474 Running cardano-node: Add checkpoints.json to config files
  docs/get-started/cardano-node/running-cardano.md
Labels: documentation

#1443 Showcase: add project Governance Space
  src/data/showcase/govspace.png
  src/data/showcases.js
Labels: showcase
